# This is a basic workflow to help you get started with Actions

name: Docker Meta

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      service_name:
        required: true
        default: gradity.io/awesome-api

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: test debug annotation
        run: echo "::debug::Set the Octocat variable"
      - name: debug service_name
        run: |
          service_name=${{github.event.inputs.service_name}}
          echo "::debug::$service_name"
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      imageTag: ${{steps.meta.outputs.tags}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{github.event.inputs.service_name}}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{steps.meta.outputs.tags}}
          
  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check Tag Name
        run: |
          echo ${{needs.build.outputs.imageTag}}
      
