name: Jobs If Tag

on:
  push:
    tags:
      - v*-dev
      - v*-prod

jobs:
  check:
    runs-on: [ubuntu-latest]
    
    outputs:
      imageTag: ${{ steps.checkbranch.outputs.resulttag }}
    
    steps:
      - uses: gradity/action-regex-match@v1.0.0
        id: regex-match
        with:
          text: ${GITHUB_REF#refs/*/}
          regexExp: /(v.*-dev)/g

      - run: echo "::notice title=regex match::${{ steps.regex-match.outputs.match }}"
  
  deploy-dev:
    needs: check
    if: ${{ needs.check.outputs.resulttag }}
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "::notice title=deploy dev::${GITHUB_REF#refs/*/}"
  
  
  deploy-prod:
    needs: check
    if: ${{ needs.check.outputs.resulttag }}
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "::notice title=deploy prod::${GITHUB_REF#refs/*/}"
  
