name: Jobs If Tag

on:
  push:
    tags:
      - v*-dev
      - v*-prod
      
jobs:
  debug:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo ${GITHUB_REF#refs/*/}
      
  check-branch:
#     if: (github.event.base_ref != 'refs/heads/production') && (endsWith(github.event.ref, 'prod'))
    runs-on: [ubuntu-latest]
    
    outputs:
      allowProduction: ${{ steps.allowProductionCheck.outputs.check }}
      
    steps:
      - name: allow production
        id: allowProductionCheck
        run: |
          if [[${{github.event.base_ref == 'refs/heads/production'}}]] && [[${{endsWith(github.event.ref, 'prod')}}]]
          then
            echo "::set-output name=check::true" 
            echo "::notice title=Allowed branch::Branch is production"
          else
            echo "::set-output name=check::false" 
            echo "::notice title=Invalid branch::Branch is not production or invalid tag for production"
          fi
        
      - run: echo ${{ steps.allowProductionCheck.outputs.check }}
        
#       - run: echo "::error title=Invalid branch::Branch is not production"
      
#   check:
#     runs-on: [ubuntu-latest]
    
#     outputs:
#       imageTag: ${{ steps.checkbranch.outputs.resulttag }}
    
#     steps:
#       - id: set
#         run: echo "::set-output name=branch::${GITHUB_REF#refs/*/}" 
        
#       - uses: actions-ecosystem/action-regex-match@v2
#         id: regex-match
#         with:
#           text: ${{ steps.set.outputs.branch}}
#           regex: '(v.*-dev)'

#       - run: echo ${{steps.regex-match.outputs.match}}
#       - run: echo "::notice title=regex match::${{ steps.regex-match.outputs.match }}"
      
  prod-test:
    needs: check-branch
#     if: (github.event.base_ref == 'refs/heads/production') && (endsWith(github.event.ref, 'prod'))
    if: needs.check-branch.outputs.allowProduction == true
    runs-on: [ubuntu-latest]
    steps:
      - run: echo ${{needs.check-branch.outputs.allowProduction}}
      - run: echo "::notice title=production test::executed test for ${GITHUB_REF#refs/*/}"
  
  deploy-dev:
    needs: check-branch
    if: (!needs.check-branch.outputs.allowProduction) && (endsWith(github.event.ref, 'dev'))
    runs-on: [ubuntu-latest]
    steps:
      - run: echo ${{needs.check-branch.outputs.allowProduction}}
      - run: echo "::notice title=deploy dev::${GITHUB_REF#refs/*/}"
  
  
  deploy-prod:
    needs: [prod-test]
    if: needs.check-branch.outputs.allowProduction == true
    runs-on: [ubuntu-latest]
    steps:
      - run: echo ${{needs.check-branch.outputs.allowProduction}}
      - run: echo "::notice title=deploy prod::${GITHUB_REF#refs/*/}"
  
