name: Jobs If Tag

on:
  push:
    tags:
      - v*-dev
      - v*-prod
      
jobs:
  debug:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo ${GITHUB_REF#refs/*/}
      
  check:
    runs-on: [ubuntu-latest]
    
    outputs:
      imageTag: ${{ steps.checkbranch.outputs.resulttag }}
    
    steps:
      - id: set
        run: echo "::set-output name=branch::${GITHUB_REF#refs/*/}" 
        
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.set.outputs.branch}}
          regex: '(v.*-dev)'

      - run: echo ${{steps.regex-match.outputs.match}}
      - run: echo "::notice title=regex match::${{ steps.regex-match.outputs.match }}"
      
  prod-test:
    needs: check
    if: true
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "::notice title=production test::executed test for ${GITHUB_REF#refs/*/}"
  
  deploy-dev:
    needs: check
    if: endsWith(github.event.ref, 'dev')
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "::notice title=deploy dev::${GITHUB_REF#refs/*/}"
  
  
  deploy-prod:
    needs: [check, prod-test]
    if: endsWith(github.event.ref, 'prod')
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "::notice title=deploy prod::${GITHUB_REF#refs/*/}"
  
