# This is a basic workflow to help you get started with Actions

name: Repo Var

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*.*.*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      service_name:
        required: true
        default: gradity.io/awesome-api

env:
  service_name: gradity.io/env-awesome-api

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: repo name
        run: ${{ env.GITHUB_ACTION_REPOSITORY }}
