# This is a basic workflow to help you get started with Actions

name: Repo Var

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*.*.*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#     inputs:
#       repo_name:
#         required: false
#         default: ${{ github.event.repository.name }}


# env:
#   og_repo: ${{ github.event.repository.name }}
#   input_repo: ${{ github.event.inputs.repo_name }}
#   REPO_NAME_SUBS: ${{ github.event.inputs.repo_name || github.event.repository.name  }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: github url
        run: echo ${{github.server.url}}/${{github.repository}}
#       - name: github url part 2
#         run: echo ${{GITHUB_SERVER_URL}}/${{github.repository}}
      - name: github url part 3
        run: echo ${GITHUB_SERVER_URL}/${{github.repository}}
#       - name: repo name from env
#         run: echo ${{ env.og_repo }}
#       - name: input repo
#         run: echo ${{ github.event.inputs.repo_name }}
#       - name: substitute repo name
#         run: echo ${{ env.REPO_NAME_SUBS }}
